### ISSUE TITLE
Build manylinux files when the new Almalinux builds are online

### ISSUE THREAD

**Issue by Jegp** [norse/aestream#17]
The current manylinux builds require us to compile GCC due to our dependence on coroutines (GCC>=10), which is just prohibitively expensive.

As soon as the manylinux project implements the CentOS continuation Almalinux, we should migrate with something like this:
```
 - uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux_2_28_poc_x86_64:poc
   with:
     python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
     build-requirements: 'cython numpy opencv-python torch flatbuffers'
     system-packages: 'ninja-build'
     pre-build-command: 'sh .github/workflows/pre-build-script.sh'
     pip-wheel-args: '-w ./dist --no-deps'
 ```
 
 And a script like:
 ```
##
## Download and install GCC, libcaer, and flatbuffers
##

# Prerequisites
yum update 
yum install -y libusb-devel

# Libcaer
git clone https://gitlab.com/inivation/dv/libcaer.git /libcaer
cd /libcaer && cmake -DCMAKE_INSTALL_PREFIX=/usr . && make -j 4 && make install

# Flatbuffers
git clone https://github.com/google/flatbuffers.git /flatbuffers
cd /flatbuffers && cmake -G "Unix Makefiles" && make -j 4 && make install
```
